#CREATE DATABASE DAVI

CREATE TABLE ALUNO(
	NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    DATA_NASCIMENTO DATE,
    ID INT NOT NULL auto_increment PRIMARY KEY
);

RENAME TABLE ALUNO TO ALUNOS;
RENAME TABLE CURSO TO CURSOS;
RENAME TABLE ALUNO_CURSO TO ALUNOS_CURSOS;