SELECT * FROM ALUNOS
SELECT NOME FROM ALUNOS
SELECT * FROM ALUNOS WHERE NOME = 'HEMELLI'
SELECT * FROM ALUNOS WHERE NOME LIKE "%DAVI%"
# O operador acima significa que o nome pode buscar em qualquer parte do nome

SELECT * FROM ALUNOS WHERE DATA_NASCIMENTO > "2000-12-31"
SELECT * FROM ALUNOS WHERE DATA_NASCIMENTO > "2000-12-31" OR NOME LIKE "%HEMELLI%"